{
 "title": "Course Service",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Number of PostgreSQL ERROR",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time ({app = \"postgres\"} |= \"authentication failed\" [5m])"
    }
   ]
  },
  {
   "title": "# Potentional Amount of Sales from Reservation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by () (sum_over_time({app=\"course-service\"} | json | message = \"booking reserved\" \n    | unwrap price [5m]))"
    }
   ]
  },
  {
   "title": "Reservation Window",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by () (count_over_time({app=\"course-service\"} | json | message=\"booking reserved\" [5m]))"
    }
   ]
  },
  {
   "title": "P95 Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.95, {app = \"course-service\"} \n    | json \n    | message = \"finished call\"\n    | unwrap grpc_time_ms [1m]) by (grpc_method, grpc_service)",
     "legendFormat": "{{grpc_service}}{{grpc_method}}"
    }
   ]
  },
  {
   "title": "# Logs Grouped by GRPC Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (grpc_code) (count_over_time({app=\"course-service\"} | json | message=\"finished call\" [1m]))",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  }
 ]
}