// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/apiclient/course/v1/booking.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_BOOKING_UNSPECIFIED Status = 0
	Status_CREATED             Status = 1
	Status_RESERVED            Status = 2
	Status_COMPLETED           Status = 3
	Status_FAILED              Status = 4
	Status_EXPIRED             Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "BOOKING_UNSPECIFIED",
		1: "CREATED",
		2: "RESERVED",
		3: "COMPLETED",
		4: "FAILED",
		5: "EXPIRED",
	}
	Status_value = map[string]int32{
		"BOOKING_UNSPECIFIED": 0,
		"CREATED":             1,
		"RESERVED":            2,
		"COMPLETED":           3,
		"FAILED":              4,
		"EXPIRED":             5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_apiclient_course_v1_booking_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_pkg_apiclient_course_v1_booking_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_apiclient_course_v1_booking_proto_rawDescGZIP(), []int{0}
}

type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Course        string                 `protobuf:"bytes,2,opt,name=course,proto3" json:"course,omitempty"`
	Batch         string                 `protobuf:"bytes,3,opt,name=batch,proto3" json:"batch,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        Status                 `protobuf:"varint,6,opt,name=status,proto3,enum=imrenagicom.demoapp.course.v1.Status" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ReservedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=reserved_at,json=reservedAt,proto3" json:"reserved_at,omitempty"`
	PaidAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	Customer      *Customer              `protobuf:"bytes,10,opt,name=customer,proto3" json:"customer,omitempty"`
	Payment       *Payment               `protobuf:"bytes,11,opt,name=payment,proto3" json:"payment,omitempty"`
	ExpiredAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	FailedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_pkg_apiclient_course_v1_booking_proto_rawDescGZIP(), []int{0}
}

func (x *Booking) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Booking) GetCourse() string {
	if x != nil {
		return x.Course
	}
	return ""
}

func (x *Booking) GetBatch() string {
	if x != nil {
		return x.Batch
	}
	return ""
}

func (x *Booking) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Booking) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Booking) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_BOOKING_UNSPECIFIED
}

func (x *Booking) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Booking) GetReservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReservedAt
	}
	return nil
}

func (x *Booking) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

func (x *Booking) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *Booking) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *Booking) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

func (x *Booking) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreetAddress string                 `protobuf:"bytes,1,opt,name=street_address,json=streetAddress,proto3" json:"street_address,omitempty"`
	AptSuite      string                 `protobuf:"bytes,2,opt,name=apt_suite,json=aptSuite,proto3" json:"apt_suite,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	ZipCode       string                 `protobuf:"bytes,5,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_pkg_apiclient_course_v1_booking_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetStreetAddress() string {
	if x != nil {
		return x.StreetAddress
	}
	return ""
}

func (x *Address) GetAptSuite() string {
	if x != nil {
		return x.AptSuite
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type Customer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email           string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber     string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	ShippingAddress *Address               `protobuf:"bytes,4,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	BillingAddress  *Address               `protobuf:"bytes,5,opt,name=billing_address,json=billingAddress,proto3" json:"billing_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_pkg_apiclient_course_v1_booking_proto_rawDescGZIP(), []int{2}
}

func (x *Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Customer) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Customer) GetShippingAddress() *Address {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *Customer) GetBillingAddress() *Address {
	if x != nil {
		return x.BillingAddress
	}
	return nil
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceNumber string                 `protobuf:"bytes,1,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_pkg_apiclient_course_v1_booking_proto_rawDescGZIP(), []int{3}
}

func (x *Payment) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

func (x *Payment) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apiclient_course_v1_booking_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBookingRequest) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type GetBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       string                 `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apiclient_course_v1_booking_proto_rawDescGZIP(), []int{5}
}

func (x *GetBookingRequest) GetBooking() string {
	if x != nil {
		return x.Booking
	}
	return ""
}

type ReserveBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       string                 `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveBookingRequest) Reset() {
	*x = ReserveBookingRequest{}
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveBookingRequest) ProtoMessage() {}

func (x *ReserveBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveBookingRequest.ProtoReflect.Descriptor instead.
func (*ReserveBookingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apiclient_course_v1_booking_proto_rawDescGZIP(), []int{6}
}

func (x *ReserveBookingRequest) GetBooking() string {
	if x != nil {
		return x.Booking
	}
	return ""
}

type ReserveBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveBookingResponse) Reset() {
	*x = ReserveBookingResponse{}
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveBookingResponse) ProtoMessage() {}

func (x *ReserveBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveBookingResponse.ProtoReflect.Descriptor instead.
func (*ReserveBookingResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apiclient_course_v1_booking_proto_rawDescGZIP(), []int{7}
}

type SetPaymentDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       string                 `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	Payment       *Payment               `protobuf:"bytes,2,opt,name=payment,proto3" json:"payment,omitempty"`
	Customer      *Customer              `protobuf:"bytes,3,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPaymentDetailRequest) Reset() {
	*x = SetPaymentDetailRequest{}
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPaymentDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPaymentDetailRequest) ProtoMessage() {}

func (x *SetPaymentDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPaymentDetailRequest.ProtoReflect.Descriptor instead.
func (*SetPaymentDetailRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apiclient_course_v1_booking_proto_rawDescGZIP(), []int{8}
}

func (x *SetPaymentDetailRequest) GetBooking() string {
	if x != nil {
		return x.Booking
	}
	return ""
}

func (x *SetPaymentDetailRequest) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *SetPaymentDetailRequest) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type SetPaymentDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPaymentDetailResponse) Reset() {
	*x = SetPaymentDetailResponse{}
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPaymentDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPaymentDetailResponse) ProtoMessage() {}

func (x *SetPaymentDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPaymentDetailResponse.ProtoReflect.Descriptor instead.
func (*SetPaymentDetailResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apiclient_course_v1_booking_proto_rawDescGZIP(), []int{9}
}

type ExpireBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       string                 `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireBookingRequest) Reset() {
	*x = ExpireBookingRequest{}
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireBookingRequest) ProtoMessage() {}

func (x *ExpireBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireBookingRequest.ProtoReflect.Descriptor instead.
func (*ExpireBookingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apiclient_course_v1_booking_proto_rawDescGZIP(), []int{10}
}

func (x *ExpireBookingRequest) GetBooking() string {
	if x != nil {
		return x.Booking
	}
	return ""
}

type ExpireBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireBookingResponse) Reset() {
	*x = ExpireBookingResponse{}
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireBookingResponse) ProtoMessage() {}

func (x *ExpireBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireBookingResponse.ProtoReflect.Descriptor instead.
func (*ExpireBookingResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apiclient_course_v1_booking_proto_rawDescGZIP(), []int{11}
}

type ListBookingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// invoice number of the booking used for filtering.
	Invoice string `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	// booking status used for filtering.
	Status        Status `protobuf:"varint,2,opt,name=status,proto3,enum=imrenagicom.demoapp.course.v1.Status" json:"status,omitempty"`
	PageSize      uint64 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OrderBy       string `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookingsRequest) Reset() {
	*x = ListBookingsRequest{}
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingsRequest) ProtoMessage() {}

func (x *ListBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingsRequest.ProtoReflect.Descriptor instead.
func (*ListBookingsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apiclient_course_v1_booking_proto_rawDescGZIP(), []int{12}
}

func (x *ListBookingsRequest) GetInvoice() string {
	if x != nil {
		return x.Invoice
	}
	return ""
}

func (x *ListBookingsRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_BOOKING_UNSPECIFIED
}

func (x *ListBookingsRequest) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListBookingsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListBookingsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListBookingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*Booking             `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookingsResponse) Reset() {
	*x = ListBookingsResponse{}
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingsResponse) ProtoMessage() {}

func (x *ListBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apiclient_course_v1_booking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingsResponse.ProtoReflect.Descriptor instead.
func (*ListBookingsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apiclient_course_v1_booking_proto_rawDescGZIP(), []int{13}
}

func (x *ListBookingsResponse) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

func (x *ListBookingsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_pkg_apiclient_course_v1_booking_proto protoreflect.FileDescriptor

const file_pkg_apiclient_course_v1_booking_proto_rawDesc = "" +
	"\n" +
	"%pkg/apiclient/course/v1/booking.proto\x12\x1dimrenagicom.demoapp.course.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x17google/api/client.proto\x1a\x19google/protobuf/any.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a%pkg/apiclient/course/v1/catalog.proto\"\xc3\x06\n" +
	"\aBooking\x12\x1c\n" +
	"\x06number\x18\x01 \x01(\tB\x04\xe2A\x01\x03R\x06number\x12>\n" +
	"\x06course\x18\x02 \x01(\tB&\xfaA#\n" +
	"!course.demoapp.imrenagicom/CourseR\x06course\x12A\n" +
	"\x05batch\x18\x03 \x01(\tB+\xfaA(\n" +
	"&course.demoapp.imrenagicom/CourseBatchR\x05batch\x12\x1a\n" +
	"\x05price\x18\x04 \x01(\x01B\x04\xe2A\x01\x03R\x05price\x12 \n" +
	"\bcurrency\x18\x05 \x01(\tB\x04\xe2A\x01\x03R\bcurrency\x12C\n" +
	"\x06status\x18\x06 \x01(\x0e2%.imrenagicom.demoapp.course.v1.StatusB\x04\xe2A\x01\x03R\x06status\x12?\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\tcreatedAt\x12A\n" +
	"\vreserved_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"reservedAt\x129\n" +
	"\apaid_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\x06paidAt\x12C\n" +
	"\bcustomer\x18\n" +
	" \x01(\v2'.imrenagicom.demoapp.course.v1.CustomerR\bcustomer\x12@\n" +
	"\apayment\x18\v \x01(\v2&.imrenagicom.demoapp.course.v1.PaymentR\apayment\x12?\n" +
	"\n" +
	"expired_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\texpiredAt\x12=\n" +
	"\tfailed_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\bfailedAt:N\xeaAK\n" +
	"\"course.demoapp.imrenagicom/Booking\x12\x12bookings/{booking}*\bbookings2\abooking\"\xac\x01\n" +
	"\aAddress\x12%\n" +
	"\x0estreet_address\x18\x01 \x01(\tR\rstreetAddress\x12\x1b\n" +
	"\tapt_suite\x18\x02 \x01(\tR\baptSuite\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x19\n" +
	"\bzip_code\x18\x05 \x01(\tR\azipCode\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\"\xfb\x01\n" +
	"\bCustomer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12Q\n" +
	"\x10shipping_address\x18\x04 \x01(\v2&.imrenagicom.demoapp.course.v1.AddressR\x0fshippingAddress\x12O\n" +
	"\x0fbilling_address\x18\x05 \x01(\v2&.imrenagicom.demoapp.course.v1.AddressR\x0ebillingAddress\"N\n" +
	"\aPayment\x12+\n" +
	"\x0einvoice_number\x18\x01 \x01(\tB\x04\xe2A\x01\x03R\rinvoiceNumber\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\"^\n" +
	"\x14CreateBookingRequest\x12F\n" +
	"\abooking\x18\x01 \x01(\v2&.imrenagicom.demoapp.course.v1.BookingB\x04\xe2A\x01\x02R\abooking\"Z\n" +
	"\x11GetBookingRequest\x12E\n" +
	"\abooking\x18\x01 \x01(\tB+\xe2A\x01\x02\xfaA$\n" +
	"\"course.demoapp.imrenagicom/BookingR\abooking\"^\n" +
	"\x15ReserveBookingRequest\x12E\n" +
	"\abooking\x18\x01 \x01(\tB+\xe2A\x01\x02\xfaA$\n" +
	"\"course.demoapp.imrenagicom/BookingR\abooking\"\x18\n" +
	"\x16ReserveBookingResponse\"\xf3\x01\n" +
	"\x17SetPaymentDetailRequest\x12E\n" +
	"\abooking\x18\x01 \x01(\tB+\xe2A\x01\x02\xfaA$\n" +
	"\"course.demoapp.imrenagicom/BookingR\abooking\x12F\n" +
	"\apayment\x18\x02 \x01(\v2&.imrenagicom.demoapp.course.v1.PaymentB\x04\xe2A\x01\x02R\apayment\x12I\n" +
	"\bcustomer\x18\x03 \x01(\v2'.imrenagicom.demoapp.course.v1.CustomerB\x04\xe2A\x01\x02R\bcustomer\"\x1a\n" +
	"\x18SetPaymentDetailResponse\"]\n" +
	"\x14ExpireBookingRequest\x12E\n" +
	"\abooking\x18\x01 \x01(\tB+\xe2A\x01\x02\xfaA$\n" +
	"\"course.demoapp.imrenagicom/BookingR\abooking\"\x17\n" +
	"\x15ExpireBookingResponse\"\xf3\x01\n" +
	"\x13ListBookingsRequest\x12F\n" +
	"\ainvoice\x18\x01 \x01(\tB,\xe2A\x01\x01\xfaA%\n" +
	"#payment.demoapp.imrenagicom/InvoiceR\ainvoice\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.imrenagicom.demoapp.course.v1.StatusR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x04R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x12\x19\n" +
	"\border_by\x18\x05 \x01(\tR\aorderBy\"\x82\x01\n" +
	"\x14ListBookingsResponse\x12B\n" +
	"\bbookings\x18\x01 \x03(\v2&.imrenagicom.demoapp.course.v1.BookingR\bbookings\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*d\n" +
	"\x06Status\x12\x17\n" +
	"\x13BOOKING_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCREATED\x10\x01\x12\f\n" +
	"\bRESERVED\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\v\n" +
	"\aEXPIRED\x10\x052\x9f\a\n" +
	"\x0eBookingService\x12\xa9\x01\n" +
	"\fListBookings\x122.imrenagicom.demoapp.course.v1.ListBookingsRequest\x1a3.imrenagicom.demoapp.course.v1.ListBookingsResponse\"0\x92A\x0e\x12\fList booking\x82\xd3\xe4\x93\x02\x19\x12\x17/api/course/v1/bookings\x12\xad\x01\n" +
	"\rCreateBooking\x123.imrenagicom.demoapp.course.v1.CreateBookingRequest\x1a&.imrenagicom.demoapp.course.v1.Booking\"?\x92A\x14\x12\x12Create new booking\x82\xd3\xe4\x93\x02\":\abooking\"\x17/api/course/v1/bookings\x12\xa1\x01\n" +
	"\n" +
	"GetBooking\x120.imrenagicom.demoapp.course.v1.GetBookingRequest\x1a&.imrenagicom.demoapp.course.v1.Booking\"9\x92A\r\x12\vGet booking\x82\xd3\xe4\x93\x02#\x12!/api/course/v1/bookings/{booking}\x12\xc7\x01\n" +
	"\x0eReserveBooking\x124.imrenagicom.demoapp.course.v1.ReserveBookingRequest\x1a5.imrenagicom.demoapp.course.v1.ReserveBookingResponse\"H\x92A\x11\x12\x0fReserve booking\x82\xd3\xe4\x93\x02.:\x01*\")/api/course/v1/bookings/{booking}:reserve\x12\xc2\x01\n" +
	"\rExpireBooking\x123.imrenagicom.demoapp.course.v1.ExpireBookingRequest\x1a4.imrenagicom.demoapp.course.v1.ExpireBookingResponse\"F\x92A\x10\x12\x0eExpire booking\x82\xd3\xe4\x93\x02-:\x01*\"(/api/course/v1/bookings/{booking}:expireB9Z7github.com/imrenagicom/demo-app/pkg/apiclient/course/v1b\x06proto3"

var (
	file_pkg_apiclient_course_v1_booking_proto_rawDescOnce sync.Once
	file_pkg_apiclient_course_v1_booking_proto_rawDescData []byte
)

func file_pkg_apiclient_course_v1_booking_proto_rawDescGZIP() []byte {
	file_pkg_apiclient_course_v1_booking_proto_rawDescOnce.Do(func() {
		file_pkg_apiclient_course_v1_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_apiclient_course_v1_booking_proto_rawDesc), len(file_pkg_apiclient_course_v1_booking_proto_rawDesc)))
	})
	return file_pkg_apiclient_course_v1_booking_proto_rawDescData
}

var file_pkg_apiclient_course_v1_booking_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_apiclient_course_v1_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_apiclient_course_v1_booking_proto_goTypes = []any{
	(Status)(0),                      // 0: imrenagicom.demoapp.course.v1.Status
	(*Booking)(nil),                  // 1: imrenagicom.demoapp.course.v1.Booking
	(*Address)(nil),                  // 2: imrenagicom.demoapp.course.v1.Address
	(*Customer)(nil),                 // 3: imrenagicom.demoapp.course.v1.Customer
	(*Payment)(nil),                  // 4: imrenagicom.demoapp.course.v1.Payment
	(*CreateBookingRequest)(nil),     // 5: imrenagicom.demoapp.course.v1.CreateBookingRequest
	(*GetBookingRequest)(nil),        // 6: imrenagicom.demoapp.course.v1.GetBookingRequest
	(*ReserveBookingRequest)(nil),    // 7: imrenagicom.demoapp.course.v1.ReserveBookingRequest
	(*ReserveBookingResponse)(nil),   // 8: imrenagicom.demoapp.course.v1.ReserveBookingResponse
	(*SetPaymentDetailRequest)(nil),  // 9: imrenagicom.demoapp.course.v1.SetPaymentDetailRequest
	(*SetPaymentDetailResponse)(nil), // 10: imrenagicom.demoapp.course.v1.SetPaymentDetailResponse
	(*ExpireBookingRequest)(nil),     // 11: imrenagicom.demoapp.course.v1.ExpireBookingRequest
	(*ExpireBookingResponse)(nil),    // 12: imrenagicom.demoapp.course.v1.ExpireBookingResponse
	(*ListBookingsRequest)(nil),      // 13: imrenagicom.demoapp.course.v1.ListBookingsRequest
	(*ListBookingsResponse)(nil),     // 14: imrenagicom.demoapp.course.v1.ListBookingsResponse
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
}
var file_pkg_apiclient_course_v1_booking_proto_depIdxs = []int32{
	0,  // 0: imrenagicom.demoapp.course.v1.Booking.status:type_name -> imrenagicom.demoapp.course.v1.Status
	15, // 1: imrenagicom.demoapp.course.v1.Booking.created_at:type_name -> google.protobuf.Timestamp
	15, // 2: imrenagicom.demoapp.course.v1.Booking.reserved_at:type_name -> google.protobuf.Timestamp
	15, // 3: imrenagicom.demoapp.course.v1.Booking.paid_at:type_name -> google.protobuf.Timestamp
	3,  // 4: imrenagicom.demoapp.course.v1.Booking.customer:type_name -> imrenagicom.demoapp.course.v1.Customer
	4,  // 5: imrenagicom.demoapp.course.v1.Booking.payment:type_name -> imrenagicom.demoapp.course.v1.Payment
	15, // 6: imrenagicom.demoapp.course.v1.Booking.expired_at:type_name -> google.protobuf.Timestamp
	15, // 7: imrenagicom.demoapp.course.v1.Booking.failed_at:type_name -> google.protobuf.Timestamp
	2,  // 8: imrenagicom.demoapp.course.v1.Customer.shipping_address:type_name -> imrenagicom.demoapp.course.v1.Address
	2,  // 9: imrenagicom.demoapp.course.v1.Customer.billing_address:type_name -> imrenagicom.demoapp.course.v1.Address
	1,  // 10: imrenagicom.demoapp.course.v1.CreateBookingRequest.booking:type_name -> imrenagicom.demoapp.course.v1.Booking
	4,  // 11: imrenagicom.demoapp.course.v1.SetPaymentDetailRequest.payment:type_name -> imrenagicom.demoapp.course.v1.Payment
	3,  // 12: imrenagicom.demoapp.course.v1.SetPaymentDetailRequest.customer:type_name -> imrenagicom.demoapp.course.v1.Customer
	0,  // 13: imrenagicom.demoapp.course.v1.ListBookingsRequest.status:type_name -> imrenagicom.demoapp.course.v1.Status
	1,  // 14: imrenagicom.demoapp.course.v1.ListBookingsResponse.bookings:type_name -> imrenagicom.demoapp.course.v1.Booking
	13, // 15: imrenagicom.demoapp.course.v1.BookingService.ListBookings:input_type -> imrenagicom.demoapp.course.v1.ListBookingsRequest
	5,  // 16: imrenagicom.demoapp.course.v1.BookingService.CreateBooking:input_type -> imrenagicom.demoapp.course.v1.CreateBookingRequest
	6,  // 17: imrenagicom.demoapp.course.v1.BookingService.GetBooking:input_type -> imrenagicom.demoapp.course.v1.GetBookingRequest
	7,  // 18: imrenagicom.demoapp.course.v1.BookingService.ReserveBooking:input_type -> imrenagicom.demoapp.course.v1.ReserveBookingRequest
	11, // 19: imrenagicom.demoapp.course.v1.BookingService.ExpireBooking:input_type -> imrenagicom.demoapp.course.v1.ExpireBookingRequest
	14, // 20: imrenagicom.demoapp.course.v1.BookingService.ListBookings:output_type -> imrenagicom.demoapp.course.v1.ListBookingsResponse
	1,  // 21: imrenagicom.demoapp.course.v1.BookingService.CreateBooking:output_type -> imrenagicom.demoapp.course.v1.Booking
	1,  // 22: imrenagicom.demoapp.course.v1.BookingService.GetBooking:output_type -> imrenagicom.demoapp.course.v1.Booking
	8,  // 23: imrenagicom.demoapp.course.v1.BookingService.ReserveBooking:output_type -> imrenagicom.demoapp.course.v1.ReserveBookingResponse
	12, // 24: imrenagicom.demoapp.course.v1.BookingService.ExpireBooking:output_type -> imrenagicom.demoapp.course.v1.ExpireBookingResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_pkg_apiclient_course_v1_booking_proto_init() }
func file_pkg_apiclient_course_v1_booking_proto_init() {
	if File_pkg_apiclient_course_v1_booking_proto != nil {
		return
	}
	file_pkg_apiclient_course_v1_catalog_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_apiclient_course_v1_booking_proto_rawDesc), len(file_pkg_apiclient_course_v1_booking_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_apiclient_course_v1_booking_proto_goTypes,
		DependencyIndexes: file_pkg_apiclient_course_v1_booking_proto_depIdxs,
		EnumInfos:         file_pkg_apiclient_course_v1_booking_proto_enumTypes,
		MessageInfos:      file_pkg_apiclient_course_v1_booking_proto_msgTypes,
	}.Build()
	File_pkg_apiclient_course_v1_booking_proto = out.File
	file_pkg_apiclient_course_v1_booking_proto_goTypes = nil
	file_pkg_apiclient_course_v1_booking_proto_depIdxs = nil
}
